name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"



[env.production.vars]
GITHUB_ID = "Ov23litxXQ3SmBxLawI1"
GITHUB_OWNER = "folkson"
GITHUB_REPO = "myNavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://1.1oo.qzz.io/api/auth"
NEXT_PUBLIC_API_URL="https://1.1oo.qzz.io"

